d_plugins = {
    "battery": ["getBattery", "onlevelchange", "updateBatteryStatus", "onchargingchange", "ondischargingtimechange"],
    "camera": ["getPicture", "cameraCallback", "CameraOptions", "PictureSourceType", "PopoverArrowDirection", "CameraPopoverHandle", "CameraPopoverOptions", "openCamera"],
    "device": ["device", "deviceready"],
    "dialogs": ["notification", "notification.alert", "notification.confirm", "notification.prompt", "notification.dismissAll", "notification.dismissPrevious", "notification.beep"],
    "file": ["resolveLocalFileSystemURL", "applicationDirectory", "applicationStorageDirectory", "dataDirectory", "cacheDirectory", "externalApplicationStorageDirectory", "externalDataDirectory", "externalCacheDirectory", "externalRootDirectory", "tempDirectory", "syncedDataDirectory", "documentsDirectory", "sharedDirectory"],
    "geolocation": ["geolocation", "getCurrentPosition", "watchPosition", "clearWatch", ""],
    "InAppBrowser": ["InAppBrowser"],
    "media": ["getCurrentAmplitude", "getCurrentPosition", "getDuration", "play", "pause", "pauseRecord", "release", "resumeRecord", "seekTo", "setVolume", "startRecord", "stopRecord", "stop", "setRate"],
    "network-information": ["connection", "checkConnection", "onOnline", "onOffline", ""],
    "screen-orientation": ["orientation", "screenLock", "screenUnlock", "orientationOnchange", "orientationType"],
    "splashscreen": ["splashscreen", "splashscreenShow", "splashscreenHide"],
    "statusbar": ["statusbar", "backgroundColorByHexString", "overlaysWebView", "backgroundColorByHexString", "styleDefault", "styleLightContent", "styleBlackTranslucent", "styleBlackOpaque", "backgroundColorByName", "backgroundColorByHexString"],
    "vibration": ["vibrate"],
}